<form action="index.php" methode="POST">
    <input type="number" name="nombre1" id="nombre1"/>
    <input type="number" name="nombre2" id="nombre2"/>
    
    <select name="operation" id="operation">
        <option value="--choisir--">operation </option>
        <option value="multiplication">multiplication X</option>
        <option value="division">Division/</option>
        <option value="soustraction">Soustraction-</option>
        <option value="modulo">Modulo %</option>

    </select>

    <input type="submit" value="Submit"/>
</form>